School_5/Controllers/EstudiantesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using School_5.Models;
using Microsoft.EntityFrameworkCore;

namespace School_5.Controllers
{
    public class EstudiantesController : Controller
    {
        private readonly School _context;

        public IActionResult Index()
        {
            var estudiantes = _context.People
                            .Where(r => r.EnrollmentDate != null)
                            .ToList();

            return View(estudiantes);
        }

        public IActionResult Ficha(int id)
        {

           // ViewData["Categorias"] = new SelectList(_context.Categories.ToList(), "CategoryID", "CategoryName");
           // ViewData["Proveedores"] = new SelectList(_context.Suppliers.ToList(), "SupplierID", "CompanyName");

            var estudiante = _context.People
                            .Where(r => r.PersonID == id)
                            .FirstOrDefault();

            return View(estudiante);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Ficha(int id, Person estudiante)
        {

            if(id != estudiante.PersonID) return NotFound();

            if(ModelState.IsValid)
            {
             _context.Update(estudiante);
             _context.SaveChanges();   
            };
            
            return View(estudiante);


        }


        public IActionResult Nuevo()
        {
           // ViewData["Categorias"] = new SelectList(_context.Categories.ToList(), "CategoryID", "CategoryName");
           // ViewData["Proveedores"] = new SelectList(_context.Suppliers.ToList(), "SupplierID", "CompanyName");

            return View("Ficha", new Person());
        }




        public EstudiantesController(School context)
        {
            _context = context;
        }
    }
}

School_5/Views/Shared/_Footer.cshtml
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - School_5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

School_5/Views/Shared/_Header.cshtml
 <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">School_5</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estudiantes" asp-action="Index">Estudiantes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departamentos" asp-action="Index">Departamentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Grados" asp-action="Index">Grados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

School_5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School_5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<body>
   

    <partial name="_Header">

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_Footer">

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>